let names = [ 
    'Elena Rhodes',
    'Jermaine Simpson',
    'Memphis Cooke',
    'Sarai Carr',
    'Greta Nichols',
    'Draven Kaiser',
    'Jaylee Mckay',
    'Jamie Castillo',
    'Marcel Leon',
    'Ashton Whitney',
    'Johnathan Ryan',
    'Nolan Klein',
    'Felicity Ortega',
    'Jaylynn Kline',
    'Dorian Simpson',
    'Milton Mann',
    'Adriel Delacruz',
    'Rey Hogan',
    'Johnny Bryant',
    'Renee Lindsey',
    'Simeon Carr',
    'Bianca Rios',
    'Byron Spence',
    'Jeffery Roberson',
    'Trent Lam',
    'Jordyn Castaneda',
    'Leia Norman',
    'Tatiana Contreras',
    'Deon Kline',
    'Arielle Harris',
    'Korbin Wilson',
    'Destinee Mcintosh',
    'Luz Larsen',
    'Anna Walsh',
    'Jace Mccarty',
    'Kenzie James',
    'Logan Roth',
    'Luis Nichols',
    'Bryson Herman',
    'Yahir Grimes',
    'Bryson Terry',
    'Cristal Cervantes',
    'Marina Vaughan',
    'Zain Russo',
    'Scarlet Moyer',
    'Michaela Vasquez',
    'Scarlett Campos',
    'Denisse Malone',
    'Mylie Jensen',
    'Chance Franco',
    'Laney Daniel',
    'Kolby Casey',
    'Madilyn Ward',
    'Reyna Bruce',
    'Tyrone Blevins',
    'Marianna Kline',
    'Zaid Booth',
    'Arianna Pierce',
    'Rubi Rosales',
    'Addison Aguilar',
    'Ayla Tran',
    'Jabari Hodge',
    'Stephanie Olsen',
    'Tatiana Maddox',
    'Leticia Haley',
    'Serena Berry',
    'Selah Green',
    'Brett Simmons',
    'Lara Mcgrath',
    'Ayden Fritz',
    'Sasha Moyer',
    'Cindy Hunter',
    'Abbey Hudson',
    'Adrianna Ashley',
    'Messiah Dudley',
    'Brice Pennington',
    'Khalil Carr',
    'Adolfo Mcfarland',
    'Clare Terrell',
    'Lilian Mccoy',
    'Ezra Gilbert',
    'Tiana Mann',
    'Melvin Howard',
    'Donald Wright',
    'Ronan Landry',
    'Yurem Myers',
    'Eduardo Donaldson',
    'Kelsie Randall',
    'Dalia Galvan',
    'Brenna Stewart',
    'Allisson Mcgee',
    'Savanah Callahan',
    'Emanuel Hebert',
    'Ty Davies',
    'Natasha Tran',
    'Kassidy Byrd',
    'Marcelo Orr',
    'Dana Lam',
    'Joseph Proctor',
    'Donald Pham',
    'Dale Reed',
    'Haley Holder',
    'Alisha Lucas',
    'Ayaan Gillespie',
    'Cristofer Carroll',
    'Alejandro Mccormick',
    'Zachery Bell',
    'Kailey Durham',
    'Kenley Dominguez',
    'Pamela Townsend',
    'Jaeden Reid',
    'Hugo Schneider',
    'Adriel Franklin',
    'Linda Stanton',
    'Leonardo Hunter',
    'Yosef Mullins',
    'Neil Walters',
    'Kameron Bowen',
    'Jerome Hayden',
    'Uriah Swanson',
    'Zayden Rivera',
    'Skylar Norton',
    'Lindsey Schaefer',
    'Amya Pacheco',
    'Maria Sampson',
    'Milo Brennan',
    'Bianca Mccormick',
    'Yusuf Wilkins',
    'Jorden Bates',
    'Kasey Wade',
    'Sammy Parker',
    'Walter Petty',
    'Lillianna Gregory',
    'Giovanna Woods',
    'Troy Maldonado',
    'Marissa Sloan',
    'Sofia Barber',
    'Imani Collins',
    'Brynlee Hodge',
    'Malik Contreras',
    'Samantha Velazquez',
    'Ryan Parks',
    'Preston Woods',
    'Kamari Horn',
    'Layton Mendez',
    'Elyse Cantu',
    'Ximena Walsh',
    'Patience Weiss',
    'Angeline Harris',
    'Devon Lara',
    'Kadyn Mccormick',
    'Andrew Hughes',
    'Amber Green',
    'Isla Huynh',
    'Kaitlin Benjamin',
    'Luke Ramos',
    'Aaden Shannon',
    'Jamiya Soto',
    'Tanya Griffin',
    'Annabella Waller',
    'Paul Hernandez',
    'Sanai Cox',
    'Sarahi Wilkins',
    'Andre Summers',
    'Jamiya Dalton',
    'Evelin Wilcox',
    'Mike Mcknight',
    'Aryan Taylor',
    'Jada Benjamin',
    'Darrell Galloway',
    'Robert Wade',
    'Jaslene Page',
    'Landin Gonzalez',
    'Reagan Price',
    'Carson Jacobson',
    'Bryce Daniels',
    'Aden Bernard',
    'Gavyn Dixon',
    'Adelaide Armstrong',
    'Porter Barrera',
    'Mariela Hines',
    'Ean Stafford',
    'Collin Walton',
    'Mylie Ramirez',
    'Aniya Porter',
    'Kenley Grant',
    'Haylee Collins',
    'Kadin Hendricks',
    'Jaslyn Weber',
    'Alvaro Barton',
    'Xzavier Vargas',
    'Melina Wong',
    'Araceli Mckee',
    'Orlando Gallegos',
    'Cole Melendez',
    'Jane Gray',
    'Camren Mueller',
    'Dwayne Knight',
    'Kason Horton',
    'Brodie Wu',
    'Benjamin Roth',
    'Ruby Wells',
    'Laney Villarreal',
    'Brendon Wallace',
    'Charlie Saunders',
    'Thaddeus Horne',
    'Cristina Meza',
    'Salvador Clements',
    'Brynn Grant',
    'Lauryn Mcmahon',
    'Marshall West',
    'Drake Camacho',
    'Lorena Blackburn',
    'Skye Haynes',
    'Valerie Joyce',
    'Kyle Bell',
    'Kaydence Edwards',
    'Janiya Petty',
    'Yareli Terry',
    'Yahir Dudley',
    'Rowan Morris',
    'Sean Sweeney',
    'Amiya Payne',
    'Bryant Brock',
    'Elliot Foster',
    'Arnav Wolf',
    'June Williamson',
    'Jamya Adams',
    'Logan Wall',
    'Lauryn Ingram',
    'Mylie Gallegos',
    'Harmony Ingram',
    'Finnegan Perkins',
    'Leonel Benitez',
    'Brendan Tanner',
    'Kyra Joseph',
    'Paula Obrien',
    'Abram Callahan',
    'Josiah Bautista',
    'Kendal Chandler',
    'Riley Guerra',
    'Ishaan Shepherd',
    'Alondra Webster',
    'Marcus Avila',
    'Jamie Nelson',
    'Eliza Blankenship',
    'Luna Mccormick',
    'Larissa Howard',
    'Lisa Harrison',
    'Beatrice Dickerson',
    'Alexia Peterson',
    'Shania Lutz',
    'Luna Gallagher',
    'Jude Villa',
    'Alfred Hendrix',
    'Bernard Velasquez',
    'Janiyah Bright',
    'Alanna Cross',
    'Lee Hernandez',
    'Gracie Shah',
    'Abel Osborne',
    'Leland Shelton',
    'Phillip Roberts',
    'Zack Moss',
    'Maverick Preston',
    'Nicholas Knox',
    'Lawrence Bell',
    'Aliya Diaz',
    'Zachery Hale',
    'Brett Ruiz',
    'Kash Beard',
    'Arthur Henderson',
    'Jordon Mckay',
    'Mary Jacobs',
    'Leanna Barber',
    'Leland Lutz',
    'Skylar Huang',
    'Josiah Bauer',
    'Israel Mcmahon',
    'Brianna Sullivan',
    'Lewis Silva',
    'Mikayla Rodgers',
    'Isabell Livingston',
    'Carter Cowan',
    'Lennon Sellers',
    'Duncan Roberts',
    'Dante Reid',
    'Jaelynn Flowers',
    'Lexi Hoffman',
    'Ezekiel Velazquez',
    'Clarence Lam',
    'Ximena Ortiz',
    'Shelby Mcclain',
    'Mathias Kelly',
    'Sage Pratt',
    'Hanna Ellis',
    'Erik Farmer',
    'Osvaldo Brewer',
    'Esperanza Walton',
    'Reid Fleming',
    'Gilberto Callahan',
    'Deacon Mcgrath',
    'Darian Marshall',
    'Carolyn Durham',
    'Nancy Oliver',
    'Thomas Davila',
    'Demetrius Bryant',
    'Miriam Mercer',
    'Zaire Atkins',
    'Alma Parrish',
    'Frank Guzman',
    'Presley Curry',
    'Alexandria Walters',
    'Cedric Hoover',
    'Amina Beasley',
    'Xzavier Horne',
    'Elsa Watson',
    'Carly Mcconnell',
    'Gerald Francis',
    'Keaton Mcdowell',
    'Aden Barron',
    'Reagan Frank',
    'Joseph Fitzgerald',
    'George Booth',
    'Adeline Alvarado',
    'Selah Nicholson',
    'Campbell Bishop',
    'Janae Burton',
    'Belinda Holder',
    'Anastasia Logan',
    'Hamza Whitehead',
    'Cheyanne Nash',
    'Jovany May',
    'Eleanor Vincent',
    'Isabella Lucas',
    'Cortez Robbins',
    'Justin Hebert',
    'Lillianna Melendez',
    'Collin Glass',
    'Abigail Wyatt',
    'Alyson Ellis',
    'Deangelo Ward',
    'Eliza Brooks',
    'Elvis Sosa',
    'Lawrence Simon',
    'Allisson Crosby',
    'Giovanni Thompson',
    'Ernest Mclaughlin',
    'Krista Hurst',
    'Felipe Leach',
    'Karma Mayer',
    'Courtney Moody',
    'Cassidy Baird',
    'Kimberly Flowers',
    'Elise Velez',
    'Alissa Fowler',
    'Julio Valentine',
    'Jaycee Parsons',
    'Darion Riddle',
    'Mohammed Logan',
    'Ada Humphrey',
    'Aliza Larsen',
    'Evan Bruce',
    'Giana Harding',
    'Anton Shea',
    'Holly Weiss',
    'Carleigh Mack',
    'Logan Richardson',
    'Kaliyah Cook',
    'Iyana Summers',
    'Cameron Mathis',
    'Leah Wilkinson',
    'Karma Yoder',
    'Alden Hill',
    'Jensen Nolan',
    'Hanna Goodman',
    'Harmony Wade',
    'Molly Doyle',
    'Kendrick Mathis',
    'Cordell Kent',
    'Brielle Melendez',
    'Lorelai Sloan',
    'Emmett Parks',
    'Julianne Stein',
    'Cheyenne Price',
    'Eve Spencer',
    'Nina Morgan',
    'Marcel Bailey',
    'Janet Oconnor',
    'Raul Schmidt',
    'Justice Odonnell',
    'Rhys Richmond',
    'Sherlyn Kline',
    'Dwayne Murillo',
    'Lorelei Bolton',
    'Megan Mcgee',
    'Ethen Rosario',
    'Kadin Mcdowell',
    'Valentin Benitez',
    'Uriel Richardson',
    'Anaya Phillips',
    'Addison Archer',
    'Heidi Carter',
    'Dominic Orozco',
    'Jamiya Castillo',
    'Jairo Henson',
    'German Page',
    'Gia Brady',
    'Erika Simon',
    'Mathias Carroll',
    'Gideon Finley',
    'Nyasia Weaver',
    'Kelsie Elliott',
    'Octavio Compton',
    'Valentin May',
    'Charlie Valencia',
    'Matias Murillo',
    'Jazlyn Compton',
    'Nia Bird',
    'Lane Gallagher',
    'Genesis Gallagher',
    'Tony Petty',
    'Rachel Mercado',
    'Uriel Gallagher',
    'Patricia Stein',
    'Esperanza Wilson',
    'Stephany Spence',
    'Jamie Dillon',
    'Alonso Lambert',
    'Paul Mcdaniel',
    'Esmeralda Short',
    'Declan Dunn',
    'Simone Neal',
    'Aspen Villarreal',
    'Gloria Cardenas',
    'Paisley Molina',
    'Jaeden Cross',
    'Jayleen Heath',
    'Neil Sheppard',
    'Lillianna Ayers',
    'Taniyah Mayer',
    'Nathaniel Small',
    'Ann Mora',
    'Maddison Stevens',
    'Lainey Daniel',
    'Adelaide Harris',
    'Dominick Richmond',
    'Theodore Hensley',
    'Clay Sheppard',
    'Aron Phelps',
    'Azaria Morgan',
    'Carleigh Hinton',
    'Sidney Hopkins',
    'Troy Lane',
    'Yesenia Carrillo',
    'Kali Spence',
    'Jayda Espinoza',
    'Ayaan Cochran',
    'Waylon Yu',
    'Kendrick Davila',
    'Janet Welch',
    'Stephanie Cooper',
    'Maxim Ryan',
    'Felipe Patrick',
    'Jimmy Sosa',
    'Gretchen Duarte',
    'Freddy Tanner',
    'Owen White',
    'Abagail Roman',
    'Kenna Erickson',
    'Kamari Morrow',
    'Noemi Werner',
    'Harper Gaines',
    'Braylen Richmond',
    'Denisse Ali',
    'Madisyn Dillon',
    'Alexa Mejia',
    'Gustavo Anthony',
    'Braiden Bowman',
    'Chelsea Whitehead',
    'Ashley Jennings',
    'Baron Shields',
    'Ramiro Butler',
    'Valentino Morse',
    'Giovanni Powell',
    'Mariela Cruz',
    'Zaid Whitehead',
    'Raquel Lee',
    'Leah Woodard',
    'Deandre Holden',
    'Mariela Stanley',
    'Selena Mccormick',
    'Miah Burnett',
    'Alberto Guerra',
    'Litzy Willis',
    'Shyann Lucas',
    'Francis Mcconnell',
    'Haley Delacruz',
    'Rowan Wong',
    'Averie Woods',
    'Elizabeth Allison',
    'Lindsay Cuevas',
    'Avery Bradshaw',
    'Camilla Gallagher',
    'Dexter Leach',
    'Clinton Pollard',
    'Makenna Pacheco',
    'Valeria Yoder',
    'Gunner Cortez',
    'Alvaro Pope',
    'Kamden Crosby',
    'Keenan Dougherty',
    'Randall Barrera',
    'Margaret Riley',
    'Maliyah Henderson',
    'Peyton Ware',
    'Alice George',
    'Quentin Wood',
    'Brandon Hudson',
    'Lexi Morrow',
    'Madilyn Rubio',
    'Kristin Andersen',
    'Marc Bowman',
    'Kendrick Morris',
    'Darian Kelly',
    'Cloe Gilbert',
    'Tobias Middleton',
    'Colt Arnold',
    'Coby King',
    'Lyric Roman',
    'Mohammad Vance',
    'Kieran Moran',
    'Nadia Jenkins',
    'Priscilla Valencia',
    'Rachel Mann',
    'Jazlyn Dean',
    'Shaun Mercado',
    'Scott Mcfarland',
    'Landyn Rivers',
    'Eliza Whitney',
    'Breanna Blake',
    'Davin Hopkins',
    'Cornelius Kirby',
    'Abram Parsons',
    'Nicole Cooley',
    'Emely Yoder',
    'Cristopher Jordan',
    'Dillon Hartman',
    'Malaki Reynolds',
    'Maryjane Brown',
    'Luciano Krause',
    'Priscilla Sawyer',
    'Zaire Hutchinson',
    'Pierce Wilkinson',
    'Blake Dawson',
    'Kathryn Gilbert',
    'Karlie Crosby',
    'Jaydin Tran',
    'Orion Love',
    'Kaylyn Hardy',
    'Chase James',
    'Lizbeth Munoz',
    'Jacoby Hays',
    'Ben Cain',
    'Eileen Mullins',
    'Shaylee Guerrero',
    'Rigoberto Chang',
    'Elian Newman',
    'Odin Wiley',
    'Kenneth Coleman',
    'King Cuevas',
    'Kareem Kaufman',
    'Heather Little',
    'Roselyn Hester',
    'Silas Holder',
    'Lizbeth Kane',
    'Charlotte Davenport',
    'Winston Zimmerman',
    'Wyatt Hicks',
    'Darian Brandt',
    'Destinee Robinson',
    'Matias Hanson',
    'Briana Roman',
    'Valeria Fletcher',
    'Samantha Newman',
    'Jakobe Villa',
    'Rachael Dominguez',
    'Jackson Pruitt',
    'Shyann Marshall',
    'Jaylee Ramsey',
    'Beckham Meyer',
    'Arjun Villarreal',
    'Memphis Whitney',
    'Arely Brady',
    'Deon Hogan',
    'Bryce Villanueva',
    'Chandler Moreno',
    'Ayla Browning',
    'Kenny Dickson',
    'Coby Sherman',
    'Quentin Gill',
    'Thaddeus Black',
    'Jayla Shaw',
    'Carmen Giles',
    'Ansley Valencia',
    'Carina Kaufman',
    'Walker Barnes',
    'Aryana Solis',
    'Cason Mcclain',
    'Sabrina French',
    'Melvin Scott',
    'Hassan Velez',
    'Kinsley Rivera',
    'Mariah Barnett',
    'Avery Kirby',
    'Macie Carey',
    'Cruz Parrish',
    'Ronin Obrien',
    'Emanuel Leblanc',
    'Skyler Sloan',
    'Melody Hogan',
    'Camila Bailey',
    'Ayla Middleton',
    'Alessandra Nolan',
    'Stephanie Vazquez',
    'Brandon Armstrong',
    'Payton Joseph',
    'Kaylee Ryan',
    'Keon Rivera',
    'Selah Greer',
    'Martin Webster',
    'Eliezer Compton',
    'Marshall Rich',
    'Kenzie Leach',
    'Riya Rocha',
    'Julian Lang',
    'Taylor Dickson',
    'Marcus Madden',
    'Laci Sparks',
    'Hayden Barber',
    'Abbigail Pineda',
    'Kelsey Kelley',
    'Yareli Bowen',
    'Sarah Dudley',
    'Ross Griffith',
    'Karma Fry',
    'Alannah Barr',
    'Christopher Ramirez',
    'Maximillian Terry',
    'Norah Duke',
    'Marshall Levy',
    'Karson Stout',
    'Ezra Mckay',
    'Ray Robbins',
    'Kamari Higgins',
    'Giovanna Mathews',
    'Nasir Castillo',
    'Darryl Buck',
    'Coby Moyer',
    'Zaid May',
    'Leonardo Reilly',
    'Mariela Bishop',
    'Terrance Nichols',
    'Erika Ritter',
    'Chace Acosta',
    'Micaela Bradford',
    'Carolyn George',
    'Garrett Bond',
    'Hector Whitaker',
    'Jonas Glass',
    'Breanna Lindsey',
    'Kyson Klein',
    'Dominique Haney',
    'Julius Morris',
    'Guadalupe Vargas',
    'Jaeden Braun',
    'Dax Palmer',
    'Emerson Nielsen',
    'Douglas Cline',
    'Alma Everett',
    'Ann Cooley',
    'Jairo Allison',
    'Kailyn Lozano',
    'Nora Black',
    'Aiyana Stevenson',
    'Abril Velasquez',
    'Jamir Byrd',
    'Lilly Salazar',
    'Erika Dean',
    'Kamari Benjamin',
    'Jamya Sims',
    'Drake George',
    'Layne Maldonado',
    'Jenny Trevino',
    'India Valentine',
    'Ansley Mejia',
    'Dalton Lam',
    'Riya Poole',
    'Keshawn Moran',
    'Lacey Montes',
    'Damon Wilcox',
    'Abdullah Banks',
    'Benjamin Austin',
    'Kira Trujillo',
    'Rex Dickson',
    'Valentino Monroe',
    'Nicole Montoya',
    'Antwan Lewis',
    'Tanya Medina',
    'Case Bennett',
    'Lydia Kent',
    'Tyree Riggs',
    'Jerimiah Lee',
    'Lamont Keller',
    'Yandel Cantrell',
    'Jean Avery',
    'Darien Heath',
    'Rafael Meyer',
    'Belen Cordova',
    'Yahir Rivera',
    'Cadence Mccarty',
    'Karter Cunningham',
    'Levi Valenzuela',
    'Cordell Bishop',
    'Max Mcgee',
    'Austin Shepherd',
    'Nicolas Cruz',
    'Tamara Hanna',
    'Alexis Duarte',
    'Alisa Stevenson',
    'Savion Boyd',
    'Jordyn Ashley',
    'Simon Buck',
    'Aryana Blevins',
    'Mylie Payne',
    'Marina Franklin',
    'Jadyn Fuentes',
    'Braylen Luna',
    'Fletcher Howard',
    'Jaylan Chan',
    'Malaki King',
    'Oscar Hurst',
    'Bryce Lambert',
    'Braylon Dunlap',
    'Evangeline Whitney',
    'Olivia Bridges',
    'Rigoberto Reyes',
    'Jax Stephenson',
    'Karly Silva',
    'Lia Rivera',
    'Landyn Nicholson',
    'Kiley Navarro',
    'Paris Cannon',
    'Gillian Cross',
    'Shannon Trujillo',
    'Bella Novak',
    'Justus Bruce',
    'Douglas White',
    'Tomas Hinton',
    'Gregory Poole',
    'Lindsay Figueroa',
    'Yasmin Montgomery',
    'Carley Crane',
    'Addison Camacho',
    'Ruth Faulkner',
    'Keshawn Gallegos',
    'Zachery Harrington',
    'Tamara Crosby',
    'Aditya Schaefer',
    'Haiden Benjamin',
    'Zander Yang',
    'Tobias Waller',
    'Josiah Benjamin',
    'Rodrigo Downs',
    'Desiree Mata',
    'Paul Roth',
    'Makayla Rodgers',
    'Graham Myers',
    'Juan Dudley',
    'Levi Alvarez',
    'Junior Moyer',
    'Lindsay Macdonald',
    'Cynthia Morales',
    'Alexandria Sweeney',
    'Katherine Hays',
    'Cameron Jackson',
    'Karen Pratt',
    'Emerson Hoffman',
    'Johnathan Evans',
    'Natalee Mendoza',
    'Vicente Beasley',
    'Caroline Todd',
    'Zackary Vazquez',
    'Zaiden Yates',
    'Evangeline Long',
    'Hamza Griffin',
    'Amya Gray',
    'Alina Potter',
    'Gavin Dudley',
    'Selina Beck',
    'Leticia Cooke',
    'Lilah Summers',
    'Clara Hansen',
    'Ahmed Simon',
    'Nelson Villa',
    'Rafael Saunders',
    'Seamus Ball',
    'Luka Hayden',
    'Donavan Villa',
    'Lilly Turner',
    'Aaliyah Williamson',
    'Lina Hood',
    'Sharon Cross',
    'Kaylah Franco',
    'Jameson Harvey',
    'Jadiel Lucero',
    'Ryder Becker',
    'Gaige Wong',
    'Karlie Dunn',
    'Lilah Berg',
    'Erik Rivera',
    'Laurel Keller',
    'Sharon Vaughan',
    'Vicente Michael',
    'Elisabeth Fritz',
    'Thalia Melton',
    'Yahir Bray',
    'Malia Solis',
    'Arnav Rosales',
    'Carley Gibbs',
    'Davion Glover',
    'Cassandra Calhoun',
    'Isabela Porter',
    'Karen Ferguson',
    'Kayden Sutton',
    'Steve Kent',
    'Aliza Compton',
    'Emily Robbins',
    'Gideon Hawkins',
    'Johnathon Montes',
    'Sandra Gutierrez',
    'Spencer Travis',
    'Jovanni Holden',
    'Catalina French',
    'Jan Fischer',
    'Bella Combs',
    'Kaitlynn Myers',
    'Landen Dickerson',
    'Crystal Wheeler',
    'Lorelai Pitts',
    'Danna Yang',
    'Ella Strickland',
    'Barbara Schroeder',
    'Yair Porter',
    'Antwan Travis',
    'Waylon Mcclure',
    'Khloe Underwood',
    'Jerry Watkins',
    'Zack Hunt',
    'Kaitlin Cooley',
    'Barbara Morrow',
    'Sebastian Frey',
    'Isai Rivas',
    'Kassandra Everett',
    'Connor Horne',
    'Braeden Scott',
    'Andrew Chambers',
    'Hayden Blanchard',
    'Krista Schaefer',
    'Diana Andrade',
    'Jorden Perez',
    'Kenyon Richardson',
    'Cora Carlson',
    'Gloria Campbell',
    'Roger Buckley',
    'Jeffrey Avery',
    'Tia Higgins',
    'Brynn Moon',
    'Jessie Mcconnell',
    'Aria Lewis',
    'Solomon Rosales',
    'Walker Harrison',
    'Tyrone Mullen',
    'Evangeline Robles',
    'Kolten Bradford',
    'Kasey Giles',
    'Mohammed Summers',
    'Kaiya Walls',
    'Cayden Wang',
    'Dax Hardin',
    'Robert Potts',
    'Xavier Browning',
    'Ximena Holmes',
    'Cedric Farley',
    'Ezekiel Patel',
    'Diego Daniel',
    'Lyric Vargas',
    'Graham Sosa',
    'Ayden Mcfarland',
    'Douglas Jimenez',
    'Ronin Reynolds',
    'Jeffrey Kemp',
    'Selah Parks',
    'Willie Higgins',
    'Jordon Wolf',
    'Maxim Nichols',
    'Madyson Wyatt',
    'Saniyah Daugherty',
    'Marley Reeves',
    'Jaida Parrish',
    'Phoenix Good',
    'Avery Coffey',
    'Natalya Crane',
    'Zaire Richmond',
    'Bradyn Stanton',
    'Joel Kaiser',
    'Joy King',
    'Rose Osborn',
    'Nehemiah Riggs',
    'Rudy Richard',
    'Karla Hurley',
    'Adison Henderson',
    'Stacy Davenport',
    'Aidyn Mendez',
    'Jairo Sawyer',
    'Sophie Hickman',
    'Zara Warren',
    'Alonso Curtis',
    'Abram Novak',
    'Brittany Lynch',
    'Sharon Mayo',
    'Trystan Mejia',
    'Eli Molina',
    'Anabella Wood',
    'Ibrahim Mcintyre',
    'Brice Monroe',
    'Braiden Villa',
    'Ashlyn Harmon',
    'Miya Schmidt',
    'Brenton Robbins',
    'Kennedy Lee',
    'Frederick Cline',
    'Miya Fitzgerald',
    'Marley Miller',
    'Robert Krause',
    'Wyatt Anderson',
    'Alfredo Wheeler',
    'Jazmyn Miller',
    'Damian Meza',
    'Aaliyah Oconnor',
    'Sadie Bentley',
    'Noel Ellison',
    'Maryjane Reeves',
    'Bridger Cuevas',
    'Shawn Bray',
    'Cristofer Baird',
    'Ellie Mckee',
    'Bo Humphrey',
    'Dwayne Moreno',
    'Ashtyn Orozco',
    'Jared Riddle',
    'Maritza Barnett',
    'Madyson Watson',
    'Talia Moreno',
    'Rylie Bernard',
    'Emiliano Abbott',
    'Dean Nielsen',
    'Kale Thornton',
    'Joshua Mooney',
    'Liam Duncan',
    'Desmond Duffy',
    'Arabella Joseph',
    'Bruno Alvarado',
    'Kiersten Morton',
    'Aracely Allen',
    'Tiffany Wheeler',
    'Mathew Hunter',
    'Alena Stanley',
    'Addisyn Cunningham',
    'Lizeth Gates',
    'Clay Clayton',
    'Josh Valencia',
    'Jayleen Vance',
    'Cornelius White',
    'Blake Miranda',
    'Jonas Stewart',
    'Tamara Kelly',
    'Jocelyn Wilkerson',
    'Troy Hill',
    'Lyric Thompson',
    'Aubree David',
    'Joslyn English',
    'Vincent Bray',
    'Yasmin Leach',
    'Javion Christensen',
    'Mina Acosta',
    'Jack Mcclain',
    'Fatima Hanson',
    'Aurora Gay',
    'Lena Gutierrez',
];


function hashcode(s) {
    let hash = 0, i, chr;
    if (s.length === 0) { 
        return hash;
    }
    for (i = 0; i < s.length; i++) {
        chr   = s.charCodeAt(i);
        hash  = ((hash << 5) - hash) + chr;
        hash |= 0; // Convert to 32bit integer
    }
    return hash;
};

function newBrowser() {
    return new webdriver.Builder().forBrowser('chrome').build();
}

async function createAccount(acc){
    let driver = newBrowser();
    driver.get('https://iexcloud.io/cloud-login#/register');
    //driver.manage().window().maximize();
   
    await driver.wait(
        until.elementLocated(By.css('form')), 10000);
   
    driver.findElement(By.css("option[value='individual']")).click()
    driver.findElement(By.id('companyName')).sendKeys(acc.name);
    driver.findElement(By.id('email')).sendKeys(acc.email);
    driver.findElement(By.id('password')).sendKeys(acc.pwd);
    driver.findElement(By.css('.showCheckBox')).click();
  

    await driver.sleep(3000);
    let submitBtn = driver.findElement(By.css('button[type="submit"]'));
    //await driver.wait(
    //    until.elementIsEnabled(submitBtn), 10000);
    submitBtn.click();

    
    await driver.wait(
        until.elementLocated(By.css('form')), 10000);


    await driver.wait(
        until.elementLocated(By.id('setup')), 60000);
    //console.log('setup');

    let buttons = await driver.findElements(By.css('button'));
    for (let i = 0; i < buttons.length; i++){
        let btn = buttons[i];        
        let label = await btn.getText();
        if (label === "Select Start plan") {
            btn.click();       
        }
    };

    await driver.wait(
        until.elementLocated(By.css('a[href="/console/tokens"]')), 60000);

    let emailPrefix = acc.email.split('@')[0];
    driver.get('https://mailnesia.com/mailbox/' + emailPrefix);

    let emailLinkLabel = 'IEX Cloud Email Verification';
    await driver.wait(async function(){
        let found = await driver.findElement(
            By.partialLinkText(emailLinkLabel)
        ).then(function (el) {
            return true;
        }).then(null, async function (err) {
            //console.log(err);
            //console.log("refresh");
            await driver.navigate().refresh();
            return false;
        })
        //console.log("result: " + found);
        return found;
    }, 60000);
    
    let verifEmailLink = await driver.findElement(
            By.partialLinkText(emailLinkLabel));

    let verifEmailHref= await verifEmailLink.getAttribute('href');

    driver.get(verifEmailHref);

    let emailDiv = await driver.wait(until.elementLocated(
        By.css('div.active')), 60000);

    let emailText = await emailDiv.getText();
    let verifLinkRE = /(https:\/\/.+)$/g;
    let match = verifLinkRE.exec(emailText);
    let verifHref = match[0].trim();

    driver.get(verifHref);

    let apiTokenEl = await driver.wait(until.elementLocated(
        By.css('.api-token-text')), 60000);

    let apiToken = await apiTokenEl.getText();

    console.log(acc.ticker + ' ' + apiToken);
    driver.close();
}

function normTicker(s) {
    return s.toUpperCase();
}

class Account {
  constructor(ticker) {
    let code = hashcode(ticker);
    let name = names[code % names.length];
    let email = name.replace(' ', '.');
    email = email.toLowerCase();
    email += '.' + code + '@mailnesia.com';
    this.email = email;
    this.pwd = 'iex!12345678';
    this.name = name;
    this.ticker = ticker;
  }

  toString() {
    return this.email + ' ' + this.pwd + ' ' + this.name;
  }
}


let args = process.argv.slice(2);
let cmd = args[0]
let ticker, acc;
let webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;



switch(cmd) {
    case 'account':
        ticker = normTicker(args[1]);
        acc = new Account(ticker);
        console.log(acc.toString());
        break;

    case 'create-account':
        ticker = normTicker(args[1]);
        acc = new Account(ticker);
        createAccount(acc);
        break;

    default:
        console.log('unknown command: ' + cmd);
        process.exit(1);
}








